### ISSUE TITLE
Warn user that username and organization name must match allowed character set

### ISSUE THREAD

**Issue by jeremiahsnapp** [chef-partners/marketplace_image#11]
At least warn the user that the username and organization name must be lowercase characters. Or just show them the full allowed character set as the docs describe them here.

http://docs.chef.io/server/ctl_chef_server.html#org-create

>The organization name must begin with a lower-case letter or digit, may only contain lower-case letters, digits, hyphens, and underscores, and must be between 1 and 255 characters.

**Comment by ryancragun** [comment]
Thanks @jeremiahsnapp.  In the next round of images we automatically [normalize](https://github.com/chef-partners/omnibus-marketplace/blob/master/files%2Fchef-marketplace-ctl-commands%2Fmarketplace%2Fhelpers.rb#L8-L14) and [validate](https://github.com/chef-partners/omnibus-marketplace/blob/master/files%2Fchef-marketplace-ctl-commands%2Fmarketplace%2Foptions.rb#L25-L55) all of the inputs.
