### ISSUE TITLE
Auto Reporting Cleanup

### ISSUE THREAD

**Issue by sean-horn** [chef-partners/marketplace_image#4]
I think maybe we need a auto cleanup for Reporting on the AMI
Note that this will only work until December with the currently shipped Reporting version

/etc/cron.d/reporting-partition-cleanup
```
YEAR=date +%Y
MONTH=date +%m
*/1 * * * * root /usr/bin/opscode-reporting-ctl remove-partitions -b $($YEAR)-$($MONTH)
```

**Comment by sean-horn** [comment]
Clarified that each Reporting package release installs and configures new partitioned tables in the opscode_reporting database on the Chef Server. To get new partitioned tables, the Reporting package must be updated regularly. During these updates, the migrations will run.

**Comment by ryancragun** [comment]
Resolved by https://github.com/chef-partners/omnibus-marketplace/commit/314c1c7bc0b2bdea2b3ee5bb40144bf49695df8f
